title: Biscuit Index
description: Comparatives of county spending on "biscuits" (i.e. frivolous items; catering services, receptions, accommodation, gifts, food and drinks, entertainment, conferences, seminars, etc...) against citizens' necessary regular spending on items that they care about.

url: https://biscuitindex.codeforkenya.org
enforce_ssl: biscuitindex.codeforkenya.org

google_analytics: G-PY4S0WY01M
